In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from pathlib import Path

In [15]:
BASE_DIR = Path.cwd()
DATA_DIR = BASE_DIR.parent.parent / "data" / "external"
print(DATA_DIR)

/Users/alilordifar/Library/CloudStorage/OneDrive-Personal/UC-Berkeley/DATASC-203-Statistics/final-project/democracy-economic-development-regression/data/external

In [81]:
gdp_per_capita = pd.read_csv(f"{DATA_DIR}/API_NY.GDP.PCAP.KD_DS2_en_csv_v2_89/API_NY.GDP.PCAP.KD_DS2_en_csv_v2_89.csv", skiprows=4)

In [82]:
#gdp_per_capita.head()

In [83]:
# Wide to Long (Melt Reshape Data From Wide to Long)
# Country | 2000 | 2001 | 2002
# USA | 10 | 12 | 14
gdp_per_capita = gdp_per_capita.drop(columns=["Indicator Name", "Indicator Code"])
gdp_per_capita = gdp_per_capita.melt(
    id_vars=["Country Name", "Country Code"],
    var_name="year",
    value_name="value"
    
)

In [84]:
#gdp_per_capita.head()

In [85]:
gdp_per_capita.shape

(17822, 4)

In [86]:
population = pd.read_csv(f"{DATA_DIR}/API_SP.POP.TOTL_DS2_en_csv_v2_58/API_SP.POP.TOTL_DS2_en_csv_v2_58.csv", skiprows=4)

In [87]:
#population.head()

In [88]:
population = population.drop(columns=["Indicator Name", "Indicator Code"])
population = population.melt(
    id_vars=["Country Name", "Country Code"],
    var_name="year",
    value_name="population"
    
)

In [89]:
#population.head()

In [90]:
# Life Expectancy in years
life_expectancy = pd.read_csv(f"{DATA_DIR}/API_SP.DYN.LE00.IN_DS2_en_csv_v2_163/API_SP.DYN.LE00.IN_DS2_en_csv_v2_163.csv", skiprows=4)

In [91]:
#life_expectancy.head()

In [92]:
life_expectancy = life_expectancy.drop(columns=["Indicator Name", "Indicator Code"])
life_expectancy = life_expectancy.melt(
    id_vars = ["Country Name", "Country Code"],
    var_name = "year",
    value_name = "life_exp"
)

In [93]:
#life_expectancy.head()

In [94]:
education = pd.read_csv(f"{DATA_DIR}/API_SE.SEC.ENRR_DS2_en_csv_v2_758/API_SE.SEC.ENRR_DS2_en_csv_v2_758.csv", skiprows=4)

In [95]:
#education

In [96]:
education = education.drop(columns=["Indicator Name", "Indicator Code"])
education = education.melt(
    id_vars=["Country Name", "Country Code"],
    var_name="year",
    value_name="education"
)

In [97]:
#education.head()

In [98]:
trade = pd.read_csv(f"{DATA_DIR}/API_NE.TRD.GNFS.ZS_DS2_en_csv_v2_101/API_NE.TRD.GNFS.ZS_DS2_en_csv_v2_101.csv", skiprows=4)
inflation = pd.read_csv(f"{DATA_DIR}/API_FP.CPI.TOTL.ZG_DS2_en_csv_v2_287/API_FP.CPI.TOTL.ZG_DS2_en_csv_v2_287.csv", skiprows=4)
unemployment = pd.read_csv(f"{DATA_DIR}/API_SL.UEM.TOTL.ZS_DS2_en_csv_v2_36/API_SL.UEM.TOTL.ZS_DS2_en_csv_v2_36.csv", skiprows=4)
urban = pd.read_csv(f"{DATA_DIR}/API_SP.URB.TOTL.IN.ZS_DS2_en_csv_v2_1412/API_SP.URB.TOTL.IN.ZS_DS2_en_csv_v2_1412.csv", skiprows=4)

In [99]:
trade = trade.drop(columns=["Indicator Name", "Indicator Code"])
inflation = inflation.drop(columns=["Indicator Name", "Indicator Code"])
unemployment = unemployment.drop(columns=["Indicator Name", "Indicator Code"])
urban = urban.drop(columns=["Indicator Name", "Indicator Code"])

In [100]:
trade = trade.melt(
    id_vars=["Country Name", "Country Code"],
    var_name="year",
    value_name="trade"
)

inflation = inflation.melt(
    id_vars=["Country Name", "Country Code"],
    var_name="year",
    value_name="inflation"
)

unemployment = unemployment.melt(
    id_vars=["Country Name", "Country Code"],
    var_name="year",
    value_name="unemployment"
)

urban = urban.melt(
    id_vars=["Country Name", "Country Code"],
    var_name="year",
    value_name="urban"
)

In [101]:
def clean_year(df):
    df = df[df["year"].str.isdigit()].copy()   # 👈 important
    df.loc[:, "year"] = df["year"].astype(int)
    return df

In [102]:
gdp_per_capita = clean_year(gdp_per_capita)
population = clean_year(population)
life_expectancy = clean_year(life_expectancy)
education = clean_year(education)
trade = clean_year(trade)
inflation = clean_year(inflation)
unemployment = clean_year(unemployment)
urban = clean_year(urban)

In [103]:
trade.head()

                  Country Name Country Code  year     trade
0                        Aruba          ABW  1960       NaN
1  Africa Eastern and Southern          AFE  1960       NaN
2                  Afghanistan          AFG  1960       NaN
3   Africa Western and Central          AFW  1960  33.02326
4                       Angola          AGO  1960       NaN

In [13]:
v_dem = pd.read_csv(f"{DATA_DIR}/V-Dem-CY-Core-v16_csv/V-Dem-CY-Core-v16.csv")

In [14]:
v_dem.head()

,country_name,country_text_id,country_id,year,historical_date,project,historical,histname,codingstart,codingend,...,v2edplural_sd,v2edplural_osp,v2edplural_osp_codelow,v2edplural_osp_codehigh,v2edplural_osp_sd,v2edplural_ord,v2edplural_ord_codelow,v2edplural_ord_codehigh,v2edplural_mean,v2edplural_nr
0,Mexico,MEX,3,1789,1789-12-31,1,1,Viceroyalty of New Spain,1789,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Mexico,MEX,3,1790,1790-12-31,1,1,Viceroyalty of New Spain,1789,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Mexico,MEX,3,1791,1791-12-31,1,1,Viceroyalty of New Spain,1789,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mexico,MEX,3,1792,1792-12-31,1,1,Viceroyalty of New Spain,1789,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mexico,MEX,3,1793,1793-12-31,1,1,Viceroyalty of New Spain,1789,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
v_dem.shape

(28092, 1908)

In [23]:
# get all columns
cols = v_dem.columns

# keep only columns that look like years
year_cols = [c for c in cols if c.isdigit() and len(c) == 4]

# optional: restrict to 2000–2022
year_cols = [c for c in year_cols if 2000 <= int(c) <= 2022]
print(year_cols)

# final columns to keep
keep_cols = ["country_name", "country_id"] + year_cols

df_dem = v_dem[keep_cols]

[]

In [22]:
df_dem

            country_name  country_id
0                 Mexico           3
1                 Mexico           3
2                 Mexico           3
3                 Mexico           3
4                 Mexico           3
...                  ...         ...
28087  Piedmont-Sardinia         373
28088  Piedmont-Sardinia         373
28089  Piedmont-Sardinia         373
28090  Piedmont-Sardinia         373
28091  Piedmont-Sardinia         373

[28092 rows x 2 columns]

In [26]:
df2 = pd.read_csv(f'{DATA_DIR}/API_NY.GDP.MKTP.KD_DS2_en_csv_v2_135/API_NY.GDP.MKTP_KD_DS2_en_csv_v2_135.csv', skiprows=4)

In [28]:
df2.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,GDP (constant 2015 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.104264e+09,3.203987e+09,3.243240e+09,2.468171e+09,2.831747e+09,3.132944e+09,3.374394e+09,3.604216e+09,NaN,NaN
1,Africa Eastern and Southern,AFE,GDP (constant 2015 US$),NY.GDP.MKTP.KD,1.543153e+11,1.549618e+11,1.672612e+11,1.766675e+11,1.848812e+11,1.943807e+11,...,9.542707e+11,9.800856e+11,9.999820e+11,9.718068e+11,1.016304e+12,1.054138e+12,1.074495e+12,1.104192e+12,NaN,NaN
2,Afghanistan,AFG,GDP (constant 2015 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.008465e+10,2.032350e+10,2.111847e+10,2.062196e+10,1.634520e+10,1.532523e+10,1.567265e+10,NaN,NaN,NaN
3,Africa Western and Central,AFW,GDP (constant 2015 US$),NY.GDP.MKTP.KD,1.103632e+11,1.124265e+11,1.166156e+11,1.248235e+11,1.315191e+11,1.369184e+11,...,7.974347e+11,8.205975e+11,8.475269e+11,8.159088e+11,8.367120e+11,8.741364e+11,9.061510e+11,9.477041e+11,NaN,NaN
4,Angola,AGO,GDP (constant 2015 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.006487e+11,1.000504e+11,9.984565e+10,9.580944e+10,9.782408e+10,1.019483e+11,1.032363e+11,1.078033e+11,NaN,NaN

In [29]:
df2.shape

(266, 71)

In [34]:
df2 = df2.drop(columns=["Indicator Name", "Indicator Code"])

df_long = df2.melt(
    id_vars=["Country Name", "Country Code"],
    var_name="year",
    value_name="value"
)

In [36]:
df_long.shape

(17822, 4)

In [39]:
df3 = pd.read_csv(f'{DATA_DIR}/API_FP.CPI.TOTL.ZG_DS2_en_csv_v2_287/API_FP.CPI.TOTL.ZG_DS2_en_csv_v2_287.csv', skiprows= 4)

In [40]:
df3

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.028282,3.626041,4.257462,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,6.221375,4.689806,4.102851,5.191629,6.824727,10.883478,7.399186,4.770857,NaN,NaN
2,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.975952,0.626149,2.302373,5.601888,5.133203,13.712102,-4.644709,-6.601186,NaN,NaN
3,Africa Western and Central,AFW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,1.725486,1.784050,1.983092,2.490378,3.745568,7.949251,5.221168,3.608044,NaN,NaN
4,Angola,AGO,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,29.844480,19.628938,17.080954,22.271539,25.754295,21.355290,13.644102,28.240495,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,1.488234,1.053798,2.675992,0.198228,3.353691,11.580510,4.944324,1.619450,NaN,NaN
262,"Yemen, Rep.",YEM,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,1.288877,2.102351,1.246275,1.337971,2.534989,4.069019,...,5.186187,4.509873,4.102851,3.232388,4.618745,7.039873,6.075244,4.361152,NaN,NaN
264,Zambia,ZMB,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,6.577312,7.494572,9.150316,15.733060,22.020768,10.993204,10.884532,14.985626,NaN,NaN
265,Zimbabwe,ZWE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,0.893962,10.618866,255.304991,557.201817,98.546105,104.705171,NaN,NaN,NaN,NaN

In [42]:
df4 = pd.read_csv(f'{DATA_DIR}/API_SP.POP.TOTL_DS2_en_csv_v2_58/API_SP.POP.TOTL_DS2_en_csv_v2_58.csv', skiprows = 4)

In [43]:
df4

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,...,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107995.0,NaN,NaN
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130075728.0,133534923.0,137171659.0,140945536.0,144904094.0,149033472.0,...,640058741.0,657801085.0,675950189.0,694446100.0,713090928.0,731821393.0,750491370.0,769280888.0,NaN,NaN
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,...,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0,NaN,NaN
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97630925.0,99706674.0,101854756.0,104089175.0,106388440.0,108772632.0,...,440882906.0,452195915.0,463365429.0,474569351.0,485920997.0,497387180.0,509398589.0,521764076.0,NaN,NaN
4,Angola,AGO,"Population, total",SP.POP.TOTL,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,...,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Population, total",SP.POP.TOTL,984846.0,1011421.0,1036950.0,1062737.0,1090270.0,1120168.0,...,1791019.0,1797086.0,1788891.0,1790151.0,1786079.0,1768096.0,1682668.0,1594353.0,NaN,NaN
262,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5532301.0,5655232.0,5782221.0,5911135.0,6048006.0,6195593.0,...,33090921.0,34085182.0,35111408.0,36134863.0,37140230.0,38222876.0,39390799.0,40583164.0,NaN,NaN
263,South Africa,ZAF,"Population, total",SP.POP.TOTL,16440172.0,16908035.0,17418522.0,17954564.0,18511361.0,19089380.0,...,57635162.0,58613001.0,59587885.0,60562381.0,61502603.0,62378410.0,63212384.0,64007187.0,NaN,NaN
264,Zambia,ZMB,"Population, total",SP.POP.TOTL,3153729.0,3254086.0,3358099.0,3465907.0,3577017.0,3692086.0,...,17441320.0,17973569.0,18513839.0,19059395.0,19603607.0,20152938.0,20723965.0,21314956.0,NaN,NaN
265,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3809389.0,3930401.0,4055959.0,4185877.0,4320006.0,4458462.0,...,14812482.0,15034452.0,15271368.0,15526888.0,15797210.0,16069056.0,16340822.0,16634373.0,NaN,NaN